language: cpp
os: linux
dist: bionic
git:
  depth: false

matrix:
  include:
    - language: python
      python: 3.5
      before_script:
        - python -m pip install -r sources/python/requirements.txt
      script:
        - python sources/python/setup.py build install




notifications:
  webhooks: https://discordapp.com/api/webhooks/299549422986067968/0TjN9PW6LcP7Nc-gqFg5nh21mDsww9Qp6vG_F8734A2d_iwPVNRUdx_xUi-xo86pvDHW/travis
