language: cpp
os: linux
dist: trusty
sudo: required

compiler:
  - g++
  
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9"

  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  
  # Go to the Root directory  
  - cd ..
  - sudo apt-get -qq update
  - sudo apt-get install -y libsfml-dev
  - git clone https://github.com/google/flatbuffers.git
  - cd flatbuffers
  - cmake -G "Unix Makefiles"
  - make
  - ./flattests
  - sudo make install
  - cd ..
  - cd src/flatbuffers/ScoreLog/
  - sh create_buffer.sh
  - cd ../../../
  - ls -la


    
# Build steps
script:
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake .. && make



