language: cpp
os: linux
dist: bionic
git:
  depth: false

matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - python -m pip install -r sources/python/requirements.txt
      script:
        - python -m pip install sources/python/
        - ls -la /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages
        - ls -la /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/DeepRTS-2.0.3.dev61-py3.6-linux-x86_64.egg
        - ls -la /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/DeepRTS-2.0.3.dev61-py3.6-linux-x86_64.egg/DeepRTS
        - ls -la /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/DeepRTS-2.0.3.dev61-py3.6-linux-x86_64.egg/DeepRTS/python
        - ls -la /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/DeepRTS-2.0.3.dev61-py3.6-linux-x86_64.egg/DeepRTS/python/test
        - python -m unittest discover DeepRTS.python.test




notifications:
  webhooks: https://discordapp.com/api/webhooks/299549422986067968/0TjN9PW6LcP7Nc-gqFg5nh21mDsww9Qp6vG_F8734A2d_iwPVNRUdx_xUi-xo86pvDHW/travis
