language: cpp
os: linux
dist: trusty
sudo: required

services:
- docker

script:
- docker build -t cair/deeprts .
- docker run -d -p 2222:22 cair/deeprts
- docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.docker.com;
    docker push cair/deeprts;
    fi